apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: LoadBalancer # Expose externally
  selector:
    app: patient
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # Match your application's port