apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: LoadBalancer # Expose externally
  selector:
    app: appointment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001 # Match your application's port